# @name get-users
GET http://localhost:3000/api/users

###

# @name post-user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "first_name": "Kleber 3",
  "last_name": "Doe43",
  "email": "74j24343@example.com",
  "password": "password"
}

###

# @name get-transactions-by-user-id
GET http://localhost:3000/api/transactions?userId=eb21cfd4-3628-4af2-9bca-42f32ea9af66

###

# @name post-transaction
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
  "userId": "eb21cfd4-3628-4af2-9bca-42f32ea9af66",
  "name": "Salário",
  "amount": 1000.00,
  "type": "EARNING",
  "date": "2023-11-27"
}

# {
#   "userId": "eb21cfd4-3628-4af2-9bca-42f32ea9af66",
#   "type": "A",
#   "amount": 1000.00,
#   "name": "Salário",
#   "date": "2023-11-27"
# }