# @name get-users
GET http://localhost:3000/api/users/93ca0d5a-eb4d-44ab-8d95-ce252ab9bfc8

###

# @name post-user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "first_name": "Leonan 2",
  "last_name": "Orth",
  "email": "leonantreste@example.com",
  "password": "teste123456"
}

###

# @name update-user
PATCH http://localhost:3000/api/users/93ca0d5a-eb4d-44ab-8d95-ce252ab9bfc8
Content-Type: application/json

{
  "first_name": "Atualizado"
}

###

# @name get-user-balance
GET http://localhost:3000/api/users/93ca0d5a-eb4d-44ab-8d95-ce252ab9bfc8/balance

###

# @name get-transactions-by-user-id
GET http://localhost:3000/api/transactions?userId=93ca0d5a-eb4d-44ab-8d95-ce252ab9bfc8

###

# @name post-transaction
POST http://localhost:3000/api/transactions
Content-Type: application/json

{
  "user_id": "93ca0d5a-eb4d-44ab-8d95-ce252ab9bfc8",
  "name": "Salário teste 231",
  "amount": 23.31,
  "type": "EXPENSE",
  "date": "2024-01-22T01:30:40.554Z"
}

###

# @name update-transactions
PATCH http://localhost:3000/api/transactions/8858077b-b76f-4c23-9d34-63c5e9a22859
Content-Type: application/json

{
  "name": "Atualizado",
  "amount": 20.00,
  "type": "EXPENSE",
  "date": "2023-11-21"
}

###

# @name delete-transaction
DELETE http://localhost:3000/api/transactions/8858077b-b76f-4c23-9d34-63c5e9a22859
Content-Type: application/json